

/* Create Tables */

CREATE TABLE BOARD_COMMENTS
(
	COMMENT_NO number(7,0) NOT NULL,
	USER_NO number(7,0) NOT NULL,
	POST_NO number(7,0) NOT NULL,
	COMMENT_CONTENT varchar2(1500) NOT NULL,
	COMMENT_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
	COMMENT_UPDATED_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (COMMENT_NO)
);


CREATE TABLE BOARD_POSTS
(
	POST_NO number(7,0) NOT NULL,
	USER_NO number(7,0) NOT NULL,
	POST_TITLE varchar2(255) NOT NULL,
	POST_CONTENT varchar2(1500) NOT NULL,
	POST_VIEW number NOT NULL,
	POST_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
	POST_UPDATED_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (POST_NO)
);


CREATE TABLE BOARD_USERS
(
	USER_NO number(7,0) NOT NULL,
	USER_ID varchar2(255) NOT NULL UNIQUE,
	USER_PASSWORD varchar2(255) NOT NULL,
	USER_NICKNAME varchar2(255) NOT NULL UNIQUE,
	USER_EMAIL varchar2(255) NOT NULL,
	USER_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
	USER_UPDATED_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (USER_NO)
);



/* Create Foreign Keys */

ALTER TABLE BOARD_COMMENTS
	ADD FOREIGN KEY (POST_NO)
	REFERENCES BOARD_POSTS (POST_NO)
;


ALTER TABLE BOARD_COMMENTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES BOARD_USERS (USER_NO)
;


ALTER TABLE BOARD_POSTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES BOARD_USERS (USER_NO)
;



